# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    disable_csrf_role: ROLE_USER
    versioning:
        enabled: true
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
    routing_loader:
        default_format: json
        include_format: false
    body_listener: true
    view:
        view_response_listener:  'force'
        formats:
            json: true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
    format_listener:
        rules:
            - { path: '^/homepage', priorities: [ 'text/html', '*/*'], fallback_format: html, prefer_extension: true }
            - { path: '^/login', priorities: [ 'text/html', '*/*'], fallback_format: html, prefer_extension: true }
            - { path: '^/logout', priorities: [ 'text/html', '*/*'], fallback_format: html, prefer_extension: true }
            - { path: '^/api', prefer_extension: true, fallback_format: json, priorities: [ json ] }
            - { path: '^/admin', priorities: [ 'text/html', '*/*'], fallback_format: html, prefer_extension: true }