vich_uploader:
    db_driver: orm

    mappings:
        user_avatar_image:
            uri_prefix: /uploads/images/user/avatar
            upload_destination: '%kernel.project_dir%/public/%app.path.user_avatar_image%'
        user_image_gallery:
          uri_prefix: /uploads/images/user/gallery
          upload_destination: '%kernel.project_dir%/public/%app.path.user_image_gallery%'
        user_video_gallery:
          uri_prefix: /uploads/videos/user/gallery
          upload_destination: '%kernel.project_dir%/public/%app.path.user_video_gallery%'
        user_video_thumbnail:
          uri_prefix: /uploads/images/user/video/thumbnail
          upload_destination: '%kernel.project_dir%/public/%app.path.user_video_thumbnail%'